# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cells}
  s.version = "2.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nick Sutterer", "Peter Bex", "Bob Leers"]
  s.date = %q{2009-12-19}
  s.description = %q{Cells are lightweight controllers for Rails and can be rendered in controllers and views, providing an elegant and fast way for encapsulation and component-orientation.}
  s.email = %q{apotonick@gmail.com}
  s.extra_rdoc_files = [
    "CHANGES",
     "README",
     "Rakefile",
     "generators/cell/USAGE",
     "generators/cell/cell_generator.rb",
     "generators/cell/templates/cell.rb",
     "generators/cell/templates/view.html.erb",
     "lib/cell/base.rb",
     "lib/cell/caching.rb",
     "lib/cell/view.rb",
     "lib/rails_extensions.rb"
  ]
  s.files = [
    "CHANGES",
     "README",
     "Rakefile",
     "generators/cell/USAGE",
     "generators/cell/cell_generator.rb",
     "generators/cell/templates/cell.rb",
     "generators/cell/templates/view.html.erb",
     "lib/cell/base.rb",
     "lib/cell/caching.rb",
     "lib/cell/view.rb",
     "lib/rails_extensions.rb"
  ]
  s.homepage = %q{http://github.com/apotonick/cells}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Cells are lightweight controllers for Rails and can be rendered in controllers and views, providing an elegant and fast way for encapsulation and component-orientation.}
  s.test_files = [
    "test/bugs_test.rb",
     "test/caching_test.rb",
     "test/cells/cells_test_one_cell.rb",
     "test/cells/cells_test_two_cell.rb",
     "test/cells/really_module/nested_cell.rb",
     "test/cells/simple_cell.rb",
     "test/cells/test_cell.rb",
     "test/cells_test.rb",
     "test/helper_test.rb",
     "test/helpers/helper_using_cell_helper.rb",
     "test/rails_extensions_test.rb",
     "test/render_test.rb",
     "test/testing_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
