source 'https://rubygems.org'

gem 'rails', '4.2.1'

gem "my_engine", path: "engines/my_engine"

gem 'sass-rails', "~> 4.0.3"#, "  ~> 3.1.0"
gem "sprockets", "~> 2.12.3"

group :development, :test do
  gem "minitest-spec-rails"
  gem "capybara_minitest_spec"
end

gem "cells", path: "../../"
gem "cells-erb", path: "../../../cells-erb"
gem "simple_form"
gem "formtastic"